spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 600000
    dynamic:
      primary: master # 显式指定主数据源为 master（与下方数据源名称匹配）
      strict: false # 关闭严格模式，允许未匹配到数据源时使用主数据源（默认 false，可选保留）
      datasource:
        master:
          #url: jdbc:sqlserver://192.168.43.88:1433;databaseName=customcert;encrypt=false
          url: jdbc:sqlserver://127.0.0.1:1433;databaseName=customcert;encrypt=false
          username: zjs
          password: 1
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver # 驼峰命名，更规范
        pojo:
          #url: jdbc:sqlserver://192.168.43.88:1433;databaseName=RJECIQ;encrypt=false
          url: jdbc:sqlserver://127.0.0.1:1433;databaseName=RJECIQ;encrypt=false
          username: zjs
          password: 1
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver # 驼峰命名，更规范
mybatis:
  configuration:
    useGeneratedKeys: true

springdoc:
  api-docs:
    path: /v3/api-docs  # OpenAPI JSON文档路径,默认就是/v3/api-docs
    enabled: true  # 启用API文档生成
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI访问路径,默认是/swagger-ui.html
    enabled: true  # 启用Swagger UI
    tags-sorter: alpha  # 标签排序方式,alpha表示按字母排序
    operations-sorter: alpha  # 操作排序方式
  show-actuator: false  # 是否显示Actuator端点,默认false

# Knife4j配置
knife4j:
  # 开启增强配置
#  enable: true
  #开启Basic登录认证功能
  setting:
    language: zh_cn  # 界面语言,zh_cn表示中文
    swagger-model-name: 实体类  # 实体类名称显示
    title: zjs的海关单据生成文档
    description: 临时试用版
    email: 13671985248@163.com
    concat: 张骏山  # 作者
    url: https://github.com/Tanxiao_Orz/CustomCert
    version: v1.0 # 版本号
  production: false  # 是否开启生产环境保护策略,生产环境建议设置为true

#  basic:
#    enable: false  # 是否启用Basic认证,默认false
#    username: admin  # Basic认证用户名
#    password: 123456  # Basic认证密码
